# I - Importation

## 1. Imporation des modules standards

In [1]:
import importlib
import os
import sys

import datetime          as dt
import numpy             as np
import pandas            as pd

import seaborn           as sns
import matplotlib.pyplot as plt

from math import ceil

## 2. Importation d'un module personnalisé

In [2]:
## Importation d'un module personnalisé
#sys.path.insert(0, r'D:\Users\User\Documents\Works\03 - Formations\02 - DataScientest\06 - Project\01 - Modules')
sys.path.insert(0,r'C:\Users\Romain Miclo\Dropbox (Compte personnel)\Formation DATA SCIENTIST\Datascientest\Projet Data Science\MODULES')


import BetPy_Annex
importlib.reload(BetPy_Annex)

from BetPy_Annex import Collect_results, Collect_infos, Aggregate_infos, Exploit_infos

ModuleNotFoundError: No module named 'BetPy_Annex'

## 3. Imporations des données + prétraitement

In [3]:
## Chargement des données
#os.chdir(r'D:\Users\User\Documents\Works\03 - Formations\02 - DataScientest\06 - Project\00 - Data\Football')
os.chdir(r'C:\Users\Romain Miclo\Dropbox (Compte personnel)\Formation DATA SCIENTIST\Datascientest\Projet Data Science\Data\Foot')

club        = pd.read_csv('club.csv', index_col='id')
match       = pd.read_csv('match.csv', index_col='id')
match_event = pd.read_csv('match_event.csv').sort_values(by=['match_id', 'matchperiod', 'eventsec'])
player      = pd.read_csv('player.csv', index_col='id')
referee     = pd.read_csv('referee.csv', index_col='id')

In [4]:
## Correction des noms de certains clubs
dico_correct = dict()
dico_correct['Angers SCO']                = 'Angers'
dico_correct['Atl\\u00e9tico Madrid']     = 'Atlético Madrid'
dico_correct['Bayern M\\u00fcnchen']      = 'Bayern München'
dico_correct['Deportivo Alav\\u00e9s']    = 'Deportivo Alavés'
dico_correct['Deportivo La Coru\\u00f1a'] = 'Deportivo La Coruña'
dico_correct['K\\u00f6ln']                = 'Köln'
dico_correct['Legan\\u00e9s']             = 'Leganés'
dico_correct['Saint']                     = 'Saint-étienne'
dico_correct['Saint-\\u00c9tienne']       = 'Saint-étienne'
dico_correct['\\u00c9tienne']             = 'Saint-étienne'

club.name                                   = club.name.replace(dico_correct)
match[['home_club', 'away_club', 'winner']] = match[['home_club', 'away_club', 'winner']].replace(dico_correct)

# Correction des lignes concernant les matchs à domicile de Saint-étienne
dico_correct = dict()
dico_correct['2017-08-05 18:00:00'] = 'Nice'
dico_correct['2017-08-19 18:00:00'] = 'Amiens SC'
dico_correct['2017-10-14 18:00:00'] = 'Metz'
dico_correct['2017-10-20 18:45:00'] = 'Montpellier'
dico_correct['2017-11-05 20:00:00'] = 'Olympique Lyonnais'
dico_correct['2017-12-15 19:45:00'] = 'Monaco'
dico_correct['2018-01-14 14:00:00'] = 'Toulouse'
dico_correct['2018-01-27 19:00:00'] = 'Caen'
dico_correct['2018-03-18 16:00:00'] = 'Guingamp'
dico_correct['2018-04-22 15:00:00'] = 'Troyes'
dico_correct['2018-05-06 13:00:00'] = 'Bordeaux'
dico_correct['2018-05-19 19:00:00'] = 'Lille'

cond = (match.home_club == 'Saint-étienne') & (match.dateutc.isin(dico_correct.keys()))
match.loc[cond, 'away_club'] = match.loc[cond, 'dateutc'].apply(lambda x: dico_correct[x])

## Re-typage + tri
match.dateutc = match.dateutc.apply(lambda x: dt.datetime.strptime(x, '%Y-%m-%d %H:%M:%S'))
match = match.sort_values(by=['dateutc'])

## Récupération du poste de chaque joueur dans la table « match_event » depuis la table « player »
match_event = match_event.join(player['position'], on='players_id')

In [5]:
## Chargement de la table « match_results » si celle-ci existe déjà
try:
    match_results = pd.read_csv('match_results.csv', index_col=0)
except FileNotFoundError:
    print("/!\ Le fichier « match_results.csv » n'existe pas encore !")

## Chargement de la table « match_infos » si celle-ci existe déjà
try:
    match_infos = pd.read_csv('match_infos.csv', index_col=0)
except FileNotFoundError:
    print("/!\ Le fichier « match_infos.csv » n'existe pas encore !")

## Chargement de la table « match_all » si celle-ci existe déjà
try:
    match_all = pd.read_csv('match_all.csv', index_col=0)
except FileNotFoundError:
    print("/!\ Le fichier « match_all.csv » n'existe pas encore !")

## Chargement de la table « data » si celle-ci existe déjà
try:
    data = pd.read_csv('data.csv', index_col=0)
except FileNotFoundError:
    print("/!\ Le fichier « data.csv » n'existe pas encore !")

# II - Création des tables contenant les variables explicatives

## 1. Création de la table « match_results » (extraction depuis la table « match »)

> <strong>Description :</strong>
>> ...

In [10]:
## Création de la table « match_results »
match_results = Collect_results(match)

## Affichage
match_results

,Date,Club,Club_ADV,Dom_Ext,Période_jour,Arbitre_id,Match_id,CLB_Série_vic,CLB_Tot_buts_pour,CLB_Tot_buts_contre,CLB_Tot_buts_diff,ADV_Série_vic,ADV_Tot_buts_pour,ADV_Tot_buts_contre,ADV_Tot_buts_diff,[Résultat],[CLB_Buts],[ADV_Buts]
0,2017-08-04 18:45:00,Monaco,Toulouse,1.0,4.0,161,759,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3,2
1,2017-08-04 18:45:00,Toulouse,Monaco,0.0,4.0,161,759,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,3
2,2017-08-05 15:15:00,PSG,Amiens SC,1.0,2.0,361,758,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2,0
3,2017-08-05 15:15:00,Amiens SC,PSG,0.0,2.0,361,758,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,2
4,2017-08-05 18:00:00,Metz,Guingamp,1.0,4.0,435,754,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2675,2018-05-20 18:45:00,Real Sociedad,Barcelona,0.0,4.0,383,760,3.0,58.0,50.0,8.0,4.0,81.0,17.0,64.0,0.0,0,1
2676,2018-05-20 18:45:00,Sassuolo,Roma,1.0,4.0,338,1,4.0,21.0,50.0,-29.0,4.0,55.0,23.0,32.0,0.0,0,1
2677,2018-05-20 18:45:00,Roma,Sassuolo,0.0,4.0,338,1,4.0,55.0,23.0,32.0,4.0,21.0,50.0,-29.0,1.0,1,0
2678,2018-05-20 18:45:00,Lazio,Internazionale,1.0,4.0,356,0,5.0,77.0,36.0,41.0,3.0,57.0,22.0,35.0,0.0,2,3
2679,2018-05-20 18:45:00,Internazionale,Lazio,0.0,4.0,356,0,3.0,57.0,22.0,35.0,5.0,77.0,36.0,41.0,1.0,3,2

In [11]:
# Écriture de la table « match_results »
match_results.to_csv('match_results.csv', sep=',')

## 2. Création de la table « match_infos » (extraction depuis la table « match_event »)

> <strong>Description :</strong>
>> ...

In [12]:
match_infos = None

## Boucle sur l'ensemble des matchs présent dans la table « match_results »
for match_id in match_results.Match_id.unique():
    # Récupération des événements du match courant
    current_match = match_event[match_event.match_id == match_id].sort_values(by=['matchperiod', 'eventsec'])
    
    # Collecte des informations sur le match courant
    meta_infos, infos = Collect_infos(current_match)
    
    # Agrégation des informations collectées ci-avant
    if match_infos is None:
        n_index, match_infos = Aggregate_infos(match_id, meta_infos, infos)
    else:
        n_index, stats = Aggregate_infos(match_id, meta_infos, infos, n_index)
        match_infos    = match_infos.append(stats)

## Affichage
match_infos

,Équipe_id,Match_id,(Possession_Équipe_1H),(Possession_Attaquants_1H),(Possession_Milieux_1H),(Possession_Défenseurs_1H),(Possession_Gardiens_1H),(Possession_Équipe_2H),(Possession_Attaquants_2H),(Possession_Milieux_2H),(Possession_Défenseurs_2H),(Possession_Gardiens_2H)
0,86,759,36.90,15.18,24.92,29.34,30.56,39.71,19.13,15.72,20.70,44.45
1,71,759,63.10,9.48,42.21,45.93,2.37,60.29,18.12,37.20,29.94,14.74
2,89,758,43.94,4.68,28.50,37.29,29.53,36.72,14.17,39.74,32.68,13.41
3,12,758,56.06,2.01,54.52,36.93,6.55,63.28,1.50,52.88,35.80,9.82
4,48,754,53.71,6.21,29.55,51.44,12.80,55.73,7.97,31.70,47.99,12.33
...,...,...,...,...,...,...,...,...,...,...,...,...
2675,15,760,55.02,34.31,18.33,40.17,7.18,53.37,12.42,30.17,34.70,22.71
2676,37,1,55.41,17.46,38.79,38.54,5.21,60.48,13.07,33.94,37.28,15.71
2677,38,1,44.59,12.78,20.94,36.37,29.91,39.52,13.18,29.55,45.51,11.75
2678,51,0,50.16,5.37,59.64,18.65,16.34,55.63,1.99,58.52,22.09,17.40
2679,53,0,49.84,0.90,49.47,44.79,4.84,44.37,11.96,37.89,40.07,10.08

In [13]:
# Écriture de la table « match_infos »
match_infos.to_csv('match_infos.csv', sep=',')

## 3. Augmentation de la table « match_infos »

> <strong>Description :</strong>
>> ...

In [14]:
## Récupération des noms des clubs dans la table « match_infos » depuis la table « club »
match_infos.insert(2, 'Club', match_infos.join(club.name, on='Équipe_id').name)

## Récupération de la date des match dans la table « match_infos » depuis la table « match_results »
match_infos.insert(0, 'Date', pd.merge(match_results[['Match_id', 'Club', 'Date']], match_infos[['Match_id', 'Club']], on=['Match_id', 'Club']).Date)

## Tri sur le champs 'Date'
match_infos = match_infos.sort_values('Date')

## Traitement des informations présentes dans « match_infos » + création de variables explicatives
match_infos = pd.concat([match_infos, Exploit_infos(match_infos)], axis=1)

## Affichage
match_infos

,Date,Équipe_id,Match_id,Club,(Possession_Équipe_1H),(Possession_Attaquants_1H),(Possession_Milieux_1H),(Possession_Défenseurs_1H),(Possession_Gardiens_1H),(Possession_Équipe_2H),...,Poss_moy_équipe_2H,Poss_moy_attaquants_2H,Poss_moy_milieux_2H,Poss_moy_défenseurs_2H,Poss_moy_gardiens_2H,Poss_moy_équipe_3H,Poss_moy_attaquants_3H,Poss_moy_milieux_3H,Poss_moy_défenseurs_3H,Poss_moy_gardiens_3H
0,2017-08-04 18:45:00,86,759,Toulouse,36.90,15.18,24.92,29.34,30.56,39.71,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017-08-04 18:45:00,71,759,Monaco,63.10,9.48,42.21,45.93,2.37,60.29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2017-08-05 15:15:00,89,758,Amiens SC,43.94,4.68,28.50,37.29,29.53,36.72,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2017-08-05 15:15:00,12,758,PSG,56.06,2.01,54.52,36.93,6.55,63.28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2017-08-05 18:00:00,48,754,Metz,53.71,6.21,29.55,51.44,12.80,55.73,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2675,2018-05-20 18:45:00,15,760,Barcelona,55.02,34.31,18.33,40.17,7.18,53.37,...,51.404,14.076,27.270,45.144,13.512,53.695,13.302,27.450,47.065,12.183
2676,2018-05-20 18:45:00,37,1,Roma,55.41,17.46,38.79,38.54,5.21,60.48,...,49.478,4.430,55.190,23.016,17.364,52.365,4.348,57.795,24.956,12.900
2677,2018-05-20 18:45:00,38,1,Sassuolo,44.59,12.78,20.94,36.37,29.91,39.52,...,56.698,7.620,38.762,40.660,12.952,56.493,6.529,38.744,41.336,13.388
2678,2018-05-20 18:45:00,51,0,Lazio,50.16,5.37,59.64,18.65,16.34,55.63,...,51.750,27.636,24.070,36.518,11.776,54.652,29.958,22.176,38.557,9.309
2679,2018-05-20 18:45:00,53,0,Internazionale,49.84,0.90,49.47,44.79,4.84,44.37,...,54.686,3.966,41.120,41.436,13.476,55.230,4.341,42.121,41.339,12.198

## 4. Création de la table « match_all »

> <strong>Description :</strong>
>> ...

In [15]:
## Jointure entre les tables « match_results » et « match_infos »
match_all = pd.merge(match_results, match_infos.drop(['Date', 'Équipe_id'], axis=1), on=['Match_id', 'Club'])

## Auto-jointure pour la récupération des variables explicatives concernant les clubs adverses
match_all = pd.merge(match_all, match_all.filter(regex='(Date|Club$|Poss_.*)', axis=1).rename(columns={'Club': 'Club_ADV'}), how='inner', on=['Date', 'Club_ADV'])

## Fonction pour le renommage des colonnes après l'auto-jointure
def renameCols(name):
    if name[-2:] == '_x':
        return 'CLB_' + name[:-2]
    elif name[-2:] == '_y':
        return 'ADV_' + name[:-2]
    else:
        return name

## Renommage des colonnes
match_all.columns = match_all.columns.map(renameCols)

## Affichage
match_all

,Date,Club,Club_ADV,Dom_Ext,Période_jour,Arbitre_id,Match_id,CLB_Série_vic,CLB_Tot_buts_pour,CLB_Tot_buts_contre,...,ADV_Poss_moy_équipe_2H,ADV_Poss_moy_attaquants_2H,ADV_Poss_moy_milieux_2H,ADV_Poss_moy_défenseurs_2H,ADV_Poss_moy_gardiens_2H,ADV_Poss_moy_équipe_3H,ADV_Poss_moy_attaquants_3H,ADV_Poss_moy_milieux_3H,ADV_Poss_moy_défenseurs_3H,ADV_Poss_moy_gardiens_3H
0,2017-08-04 18:45:00,Monaco,Toulouse,1.0,4.0,161,759,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017-08-04 18:45:00,Toulouse,Monaco,0.0,4.0,161,759,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2017-08-05 15:15:00,PSG,Amiens SC,1.0,2.0,361,758,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2017-08-05 15:15:00,Amiens SC,PSG,0.0,2.0,361,758,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2017-08-05 18:00:00,Metz,Guingamp,1.0,4.0,435,754,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2675,2018-05-20 18:45:00,Real Sociedad,Barcelona,0.0,4.0,383,760,3.0,58.0,50.0,...,51.404,14.076,27.270,45.144,13.512,53.695,13.302,27.450,47.065,12.183
2676,2018-05-20 18:45:00,Sassuolo,Roma,1.0,4.0,338,1,4.0,21.0,50.0,...,49.478,4.430,55.190,23.016,17.364,52.365,4.348,57.795,24.956,12.900
2677,2018-05-20 18:45:00,Roma,Sassuolo,0.0,4.0,338,1,4.0,55.0,23.0,...,56.698,7.620,38.762,40.660,12.952,56.493,6.529,38.744,41.336,13.388
2678,2018-05-20 18:45:00,Lazio,Internazionale,1.0,4.0,356,0,5.0,77.0,36.0,...,54.686,3.966,41.120,41.436,13.476,55.230,4.341,42.121,41.339,12.198
2679,2018-05-20 18:45:00,Internazionale,Lazio,0.0,4.0,356,0,3.0,57.0,22.0,...,51.750,27.636,24.070,36.518,11.776,54.652,29.958,22.176,38.557,9.309

In [31]:
## Autre type d'affichage (ici sur les 2 dernières lignes)
match_all.iloc[-4:, :].T

,2676,2677,2678,2679
Date,2018-05-20 18:45:00,2018-05-20 18:45:00,2018-05-20 18:45:00,2018-05-20 18:45:00
Club,Sassuolo,Roma,Lazio,Internazionale
Club_ADV,Roma,Sassuolo,Internazionale,Lazio
Dom_Ext,1,0,1,0
Période_jour,4,4,4,4
Arbitre_id,338,338,356,356
Match_id,1,1,0,0
CLB_Série_vic,4,4,5,3
CLB_Tot_buts_pour,21,55,77,57
CLB_Tot_buts_contre,50,23,36,22
CLB_Tot_buts_diff,-29,32,41,35
ADV_Série_vic,4,4,3,5
ADV_Tot_buts_pour,55,21,57,77
ADV_Tot_buts_contre,23,50,22,36
ADV_Tot_buts_diff,32,-29,35,41
[Résultat],0,1,0,1
[CLB_Buts],0,1,2,3
[ADV_Buts],1,0,3,2
(Possession_Équipe_1H),44.59,55.41,50.16,49.84
(Possession_Attaquants_1H),12.78,17.46,5.37,0.9
(Possession_Milieux_1H),20.94,38.79,59.64,49.47
(Possession_Défenseurs_1H),36.37,38.54,18.65,44.79
(Possession_Gardiens_1H),29.91,5.21,16.34,4.84
(Possession_Équipe_2H),39.52,60.48,55.63,44.37
(Possession_Attaquants_2H),13.18,13.07,1.99,11.96
(Possession_Milieux_2H),29.55,33.94,58.52,37.89
(Possession_Défenseurs_2H),45.51,37.28,22.09,40.07
(Possession_Gardiens_2H),11.75,15.71,17.4,10.08
CLB_Poss_moy_équipe_1H,56.288,55.252,57.554,55.774
CLB_Poss_moy_attaquants_1H,5.438,4.266,32.28,4.716
CLB_Poss_moy_milieux_1H,38.726,60.4,20.282,43.122
CLB_Poss_moy_défenseurs_1H,42.012,26.896,40.596,41.242
CLB_Poss_moy_gardiens_1H,13.824,8.436,6.842,10.92
CLB_Poss_moy_équipe_2H,56.698,49.478,51.75,54.686
CLB_Poss_moy_attaquants_2H,7.62,4.43,27.636,3.966
CLB_Poss_moy_milieux_2H,38.762,55.19,24.07,41.12
CLB_Poss_moy_défenseurs_2H,40.66,23.016,36.518,41.436
CLB_Poss_moy_gardiens_2H,12.952,17.364,11.776,13.476
CLB_Poss_moy_équipe_3H,56.493,52.365,54.652,55.23
CLB_Poss_moy_attaquants_3H,6.529,4.348,29.958,4.341
CLB_Poss_moy_milieux_3H,38.744,57.795,22.176,42.121
CLB_Poss_moy_défenseurs_3H,41.336,24.956,38.557,41.339
CLB_Poss_moy_gardiens_3H,13.388,12.9,9.309,12.198
ADV_Poss_moy_équipe_1H,55.252,56.288,55.774,57.554
ADV_Poss_moy_attaquants_1H,4.266,5.438,4.716,32.28
ADV_Poss_moy_milieux_1H,60.4,38.726,43.122,20.282
ADV_Poss_moy_défenseurs_1H,26.896,42.012,41.242,40.596
ADV_Poss_moy_gardiens_1H,8.436,13.824,10.92,6.842
ADV_Poss_moy_équipe_2H,49.478,56.698,54.686,51.75
ADV_Poss_moy_attaquants_2H,4.43,7.62,3.966,27.636
ADV_Poss_moy_milieux_2H,55.19,38.762,41.12,24.07
ADV_Poss_moy_défenseurs_2H,23.016,40.66,41.436,36.518
ADV_Poss_moy_gardiens_2H,17.364,12.952,13.476,11.776
ADV_Poss_moy_équipe_3H,52.365,56.493,55.23,54.652
ADV_Poss_moy_attaquants_3H,4.348,6.529,4.341,29.958
ADV_Poss_moy_milieux_3H,57.795,38.744,42.121,22.176
ADV_Poss_moy_défenseurs_3H,24.956,41.336,41.339,38.557
ADV_Poss_moy_gardiens_3H,12.9,13.388,12.198,9.309

In [32]:
# Écriture de la table « match_all »
match_all.to_csv('match_all.csv', sep=',')

## 5. Création de la table « data »

> <strong>Description :</strong>
>> ...

In [33]:
## Suppression des lignes ayant des NA dans la table « match_all »
match_all = match_all.dropna()

## Création de la table « data »
data                          = pd.DataFrame(match_all['Dom_Ext'])

data['Écart_buts_diff']       = match_all['CLB_Tot_buts_diff']          - match_all['ADV_Tot_buts_diff']
data['Écart_buts_pour']       = match_all['CLB_Tot_buts_pour']          - match_all['ADV_Tot_buts_pour']
data['Écart_buts_contre']     = match_all['ADV_Tot_buts_contre']        - match_all['CLB_Tot_buts_contre']

data['Écart_Poss_moy_éq_1H']  = match_all['CLB_Poss_moy_équipe_1H']     - match_all['ADV_Poss_moy_équipe_1H']
data['Écart_Poss_moy_att_1H'] = match_all['CLB_Poss_moy_attaquants_1H'] - match_all['ADV_Poss_moy_attaquants_1H']
data['Écart_Poss_moy_mil_1H'] = match_all['CLB_Poss_moy_milieux_1H']    - match_all['ADV_Poss_moy_milieux_1H']
data['Écart_Poss_moy_def_1H'] = match_all['CLB_Poss_moy_défenseurs_1H'] - match_all['ADV_Poss_moy_défenseurs_1H']
data['Écart_Poss_moy_gar_1H'] = match_all['CLB_Poss_moy_gardiens_1H']   - match_all['ADV_Poss_moy_gardiens_1H']
data['Écart_Poss_moy_éq_2H']  = match_all['CLB_Poss_moy_équipe_2H']     - match_all['ADV_Poss_moy_équipe_2H']
data['Écart_Poss_moy_att_2H'] = match_all['CLB_Poss_moy_attaquants_2H'] - match_all['ADV_Poss_moy_attaquants_2H']
data['Écart_Poss_moy_mil_2H'] = match_all['CLB_Poss_moy_milieux_2H']    - match_all['ADV_Poss_moy_milieux_2H']
data['Écart_Poss_moy_def_2H'] = match_all['CLB_Poss_moy_défenseurs_2H'] - match_all['ADV_Poss_moy_défenseurs_2H']
data['Écart_Poss_moy_gar_2H'] = match_all['CLB_Poss_moy_gardiens_2H']   - match_all['ADV_Poss_moy_gardiens_2H']
data['Écart_Poss_moy_éq_3H']  = match_all['CLB_Poss_moy_équipe_3H']     - match_all['ADV_Poss_moy_équipe_3H']
data['Écart_Poss_moy_att_3H'] = match_all['CLB_Poss_moy_attaquants_3H'] - match_all['ADV_Poss_moy_attaquants_3H']
data['Écart_Poss_moy_mil_3H'] = match_all['CLB_Poss_moy_milieux_3H']    - match_all['ADV_Poss_moy_milieux_3H']
data['Écart_Poss_moy_def_3H'] = match_all['CLB_Poss_moy_défenseurs_3H'] - match_all['ADV_Poss_moy_défenseurs_3H']
data['Écart_Poss_moy_gar_3H'] = match_all['CLB_Poss_moy_gardiens_3H']   - match_all['ADV_Poss_moy_gardiens_3H']

data['[Résultat]']            = match_all['[Résultat]']

## Affichage
data

,Dom_Ext,Écart_buts_diff,Écart_buts_pour,Écart_buts_contre,Écart_Poss_moy_éq_1H,Écart_Poss_moy_att_1H,Écart_Poss_moy_mil_1H,Écart_Poss_moy_def_1H,Écart_Poss_moy_gar_1H,Écart_Poss_moy_éq_2H,Écart_Poss_moy_att_2H,Écart_Poss_moy_mil_2H,Écart_Poss_moy_def_2H,Écart_Poss_moy_gar_2H,Écart_Poss_moy_éq_3H,Écart_Poss_moy_att_3H,Écart_Poss_moy_mil_3H,Écart_Poss_moy_def_3H,Écart_Poss_moy_gar_3H,[Résultat]
426,1.0,6.0,1.0,5.0,1.866,10.354,2.644,-9.668,-3.324,1.980,10.156,-2.310,-11.810,3.970,1.923,10.255,0.167,-10.739,0.323,1.0
427,0.0,-6.0,-1.0,-5.0,-1.866,-10.354,-2.644,9.668,3.324,-1.980,-10.156,2.310,11.810,-3.970,-1.923,-10.255,-0.167,10.739,-0.323,0.0
448,1.0,-3.0,-2.0,-1.0,-7.784,-6.510,-2.278,14.446,-5.652,-6.282,-3.476,-19.334,11.020,11.790,-7.033,-4.993,-10.806,12.733,3.069,1.0
449,0.0,3.0,2.0,1.0,7.784,6.510,2.278,-14.446,5.652,6.282,3.476,19.334,-11.020,-11.790,7.033,4.993,10.806,-12.733,-3.069,0.0
462,1.0,3.0,0.0,3.0,8.648,1.032,2.760,4.348,-8.140,6.170,0.252,11.912,4.616,-16.776,7.409,0.642,7.336,4.482,-12.458,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2675,0.0,-56.0,-23.0,-33.0,-5.908,3.808,-2.742,-8.926,7.860,-2.708,2.496,-6.412,-5.138,9.054,-4.308,3.152,-4.577,-7.032,8.457,0.0
2676,1.0,-61.0,-34.0,-27.0,1.036,1.172,-21.674,15.116,5.388,7.220,3.190,-16.428,17.644,-4.412,4.128,2.181,-19.051,16.380,0.488,0.0
2677,0.0,61.0,34.0,27.0,-1.036,-1.172,21.674,-15.116,-5.388,-7.220,-3.190,16.428,-17.644,4.412,-4.128,-2.181,19.051,-16.380,-0.488,1.0
2678,1.0,6.0,20.0,-14.0,1.780,27.564,-22.840,-0.646,-4.078,-2.936,23.670,-17.050,-4.918,-1.700,-0.578,25.617,-19.945,-2.782,-2.889,0.0
2679,0.0,-6.0,-20.0,14.0,-1.780,-27.564,22.840,0.646,4.078,2.936,-23.670,17.050,4.918,1.700,0.578,-25.617,19.945,2.782,2.889,1.0

In [6]:
# Écriture de la table « data »
data.to_csv('data.csv', sep=',')

# III - Séparation du Jeux De Données

In [126]:
## Suppression des lignes pour lesquels il manque des données
data = data.dropna()

# Recommandation de Maxime => utiliser le train_test_split mais avec l'argument de shuffle=False

## Séparation des données pour entraînement des modèles
#  -> les données sont triées dans l'ordre où les matchs se sont déroulés
X_train = data.drop('[Résultat]', axis=1).iloc[:int(ceil(.8 * len(data))),  :]
X_test  = data.drop('[Résultat]', axis=1).iloc[int(ceil(-.2 * len(data))):, :]

y_train = data[['[Résultat]']].iloc[:int(ceil(.8 * len(data))),  :]
y_test  = data[['[Résultat]']].iloc[int(ceil(-.2 * len(data))):, :] 
# ne mettre qu'une seule "paire" de [ ] pour les data
# avec cette modif peut-être plus besoin après du np.ravel()

# Changement dimensions suite au commentaire plus bas
y_train=np.ravel(y_train)
y_test=np.ravel(y_test)

# IV - Entraînement des modèles
## 1. Imporation des modules standards

In [111]:
# Import des bibliothèques
from sklearn import preprocessing
from sklearn import svm
from sklearn import model_selection

## 2. Standardisation des données

In [115]:
# Instanciation scaler et application à X_train SAUF sur le fait d'être à domicile ou à l'extérieur
X_train2=X_train.drop(["Dom_Ext"],axis=1)
X_test2=X_test.drop(["Dom_Ext"],axis=1)
Dom_Ext_train=X_train["Dom_Ext"]
Dom_Ext_test=X_test["Dom_Ext"]
# On garde les index en mémoire
index_train=X_train.index
index_test=X_test.index

scaler = preprocessing.StandardScaler().fit(X_train2)
X_train_scaled=scaler.transform(X_train2)
#Puis standardiser la partie X_test sur le même scaler :
X_test_scaled=scaler.transform(X_test2)

# Puis on vient remettre le champ domicile ou extérieur et les index
X_train_scaled=pd.DataFrame(X_train_scaled)
X_train_scaled.index=index_train
X_train_scaled.insert(0,"Dom_Ext",Dom_Ext_train,True)

X_test_scaled=pd.DataFrame(X_test_scaled)
X_test_scaled.index=index_test
X_test_scaled.insert(0,"Dom_Ext",Dom_Ext_test,True)
X_test_scaled.head()

# Et enfin on remet le nom des colonnes
X_train_scaled.columns=X_train.columns
X_test_scaled.columns=X_test.columns

## 3. Entraînement de différents algorithmes
Pour comparer le modèles entre eux, choix de la graine aléatoire à 123.
### A. GridSearch SVM

In [109]:
# Test sur des algorithmes unitaires

# Création d'un classificateur SVM
clf=svm.SVC(gamma=0.01,kernel='poly')

parametres={"C":[0.1,1,10],"kernel":['rbf', 'linear','poly'],"gamma":[0.001, 0.1, 0.5]}
grid_clf=model_selection.GridSearchCV(estimator=clf,param_grid=parametres,random_state=123)

grille = grid_clf.fit(X_train_scaled,y_train)

C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Romain Miclo\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

In [150]:
print(pd.DataFrame.from_dict(grille.cv_results_).loc[:,["params","mean_test_score"]])
print("\nLes meilleurs paramètres de la grille de recherche sont : ",grid_clf.best_params_)

                                            params  mean_test_score
0      {'C': 0.1, 'gamma': 0.001, 'kernel': 'rbf'}         0.680171
1   {'C': 0.1, 'gamma': 0.001, 'kernel': 'linear'}         0.694283
2     {'C': 0.1, 'gamma': 0.001, 'kernel': 'poly'}         0.531378
3        {'C': 0.1, 'gamma': 0.1, 'kernel': 'rbf'}         0.691342
4     {'C': 0.1, 'gamma': 0.1, 'kernel': 'linear'}         0.694283
5       {'C': 0.1, 'gamma': 0.1, 'kernel': 'poly'}         0.647276
6        {'C': 0.1, 'gamma': 0.5, 'kernel': 'rbf'}         0.530209
7     {'C': 0.1, 'gamma': 0.5, 'kernel': 'linear'}         0.694283
8       {'C': 0.1, 'gamma': 0.5, 'kernel': 'poly'}         0.637863
9        {'C': 1, 'gamma': 0.001, 'kernel': 'rbf'}         0.687811
10    {'C': 1, 'gamma': 0.001, 'kernel': 'linear'}         0.691927
11      {'C': 1, 'gamma': 0.001, 'kernel': 'poly'}         0.531378
12         {'C': 1, 'gamma': 0.1, 'kernel': 'rbf'}         0.674873
13      {'C': 1, 'gamma': 0.1, 'kernel': 'linear'}         0.691927
14        {'C': 1, 'gamma': 0.1, 'kernel': 'poly'}         0.630226
15         {'C': 1, 'gamma': 0.5, 'kernel': 'rbf'}         0.620818
16      {'C': 1, 'gamma': 0.5, 'kernel': 'linear'}         0.691927
17        {'C': 1, 'gamma': 0.5, 'kernel': 'poly'}         0.625517
18      {'C': 10, 'gamma': 0.001, 'kernel': 'rbf'}         0.704868
19   {'C': 10, 'gamma': 0.001, 'kernel': 'linear'}         0.693100
20     {'C': 10, 'gamma': 0.001, 'kernel': 'poly'}         0.531378
21        {'C': 10, 'gamma': 0.1, 'kernel': 'rbf'}         0.624904
22     {'C': 10, 'gamma': 0.1, 'kernel': 'linear'}         0.693100
23       {'C': 10, 'gamma': 0.1, 'kernel': 'poly'}         0.638441
24        {'C': 10, 'gamma': 0.5, 'kernel': 'rbf'}         0.612569
25     {'C': 10, 'gamma': 0.5, 'kernel': 'linear'}         0.693100
26       {'C': 10, 'gamma': 0.5, 'kernel': 'poly'}         0.607278

Les meilleurs paramètres de la grille de recherche sont :  {'C': 10, 'gamma': 0.001, 'kernel': 'rbf'}

In [159]:
# Application sur les meilleurs paramètres
clf=svm.SVC(gamma=0.001,kernel='rbf',C=10,random_state=123)
clf.fit(X_train_scaled, y_train)
y_pred=clf.predict(X_test_scaled)
print("Score de la prédiction : ","%.3f"%clf.score(X_test_scaled,y_test))
pd.crosstab(y_test, y_pred, rownames=['Classe réelle'], colnames=['Classe prédite'])

Score de la prédiction :  0.69

Classe prédite  0.0  1.0
Classe réelle
0.0             147   66
1.0              65  147

### B. KNN

In [160]:
from sklearn import neighbors
knn=neighbors.KNeighborsClassifier(n_neighbors=7,metric="minkowski")
knn.fit(X_train_scaled, y_train)
y_pred=knn.predict(X_test_scaled)
print("Score de la prédiction : ","%.3f"%knn.score(X_test_scaled,y_test))
pd.crosstab(y_test, y_pred, rownames=['Classe réelle'], colnames=['Classe prédite'])

Score de la prédiction :  0.626

Classe prédite  0.0  1.0
Classe réelle
0.0             133   80
1.0              79  133

## C. Random Forest

In [161]:
from sklearn import ensemble 
clf=ensemble.RandomForestClassifier(n_jobs=-1,random_state=123) 
clf.fit(X_train_scaled,y_train)
y_pred=clf.predict(X_test_scaled)
print("Score de la prédiction : ","%.3f"%clf.score(X_test_scaled,y_test))
pd.crosstab(y_test, y_pred, rownames=['Classe réelle'], colnames=['Classe prédite'])

Score de la prédiction :  0.687

Classe prédite  0.0  1.0
Classe réelle
0.0             146   67
1.0              66  146

# V - Evaluation des résultats

In [98]:
# Pour le moment des résultats entre 62 et 69% d'accuracy
# Certainement voir des compositions d'algo et de grilles de recherche sur les classifieurs "simples"
# En plus des matrices de confusion, mettre le tableau complet des résultats avec f1-score...
# Mais surtout besoin d'aller certainement renforcer le jeu de données d'entrée avec des éléments important.


# Point 07/05 avec Maxime :
# Voir les modifs au niveau du train et test
# Aller chercher de meilleurs algo de classifications (celui de FB ?, en voire d'autres voire de les combiner)
# Cibles => 75% sera déjà très bien + commencer à réfléchir au rendu et au Streamlit à réaliser pour la soutenance
# Rappel prez => 20 minutes (10 minutes ppt + 10 minutes Streamlit pour démo live) + 5 minutes de question