<img src="https://datascientest.fr/train/assets/logo_datascientest.png" style="height:150px">

<hr style="border-width:2px;border-color:#75DFC1">
<center><h1> Projet paris sportif </h1></center>
<center><h2> Bet-py </h2></center>
<center><h3> Notebook : de l'import des données de base à la création des tables intermédiaires et "match_all" </h3></center>
<hr style="border-width:2px;border-color:#75DFC1">

### Sommaire  :
> <strong> I - Importations</strong>
>> 1. Importation des modules standards
>> 2. Importation d'un module personnalisé
>> 3. Importations des données + prétraitement

> <strong>II - Création des tables contenant les variables explicatives</strong>
>> 1. Création de la table « match_results » (extraction depuis la table « match »)
>> 2. Création de la table « match_infos » (extraction depuis la table « match_event »)
>> 3. Augmentation de la table « match_infos »
>> 4. Création de la table « match_all »

## I - Importations

### 1. Importation des modules standards

In [1]:
import importlib
import os
import sys

import datetime          as dt
import numpy             as np
import pandas            as pd

from math import ceil

### 2. Importation d'un module personnalisé

In [3]:
## Importation d'un module personnalisé
#sys.path.insert(0, r'D:\Users\User\Documents\Works\03 - Formations\02 - DataScientest\06 - Project\01 - Modules')
sys.path.insert(0,r'C:\Users\Romain Miclo\Dropbox (Compte personnel)\Formation DATA SCIENTIST\Datascientest\Projet Data Science\Repository\BET_PY_\4 - Module')

import BetPy_Annex
importlib.reload(BetPy_Annex)

from BetPy_Annex import Collect_results, Collect_infos, Aggregate_infos, Exploit_infos

### 3. Importations des données + prétraitement

In [4]:
## Chargement des données
#os.chdir(r'D:\Users\User\Documents\Works\03 - Formations\02 - DataScientest\06 - Project\00 - Data\Football')
os.chdir(r'C:\Users\Romain Miclo\Dropbox (Compte personnel)\Formation DATA SCIENTIST\Datascientest\Projet Data Science\Data\Foot')


club        = pd.read_csv('club.csv', index_col='id')
match       = pd.read_csv('match.csv', index_col='id')
match_event = pd.read_csv('match_event.csv').sort_values(by=['match_id', 'matchperiod', 'eventsec'])
player      = pd.read_csv('player.csv', index_col='id')
referee     = pd.read_csv('referee.csv', index_col='id')

In [5]:
## Correction des noms de certains clubs
dico_correct = dict()
dico_correct['Angers SCO']                = 'Angers'
dico_correct['Atl\\u00e9tico Madrid']     = 'Atlético Madrid'
dico_correct['Bayern M\\u00fcnchen']      = 'Bayern München'
dico_correct['Deportivo Alav\\u00e9s']    = 'Deportivo Alavés'
dico_correct['Deportivo La Coru\\u00f1a'] = 'Deportivo La Coruña'
dico_correct['K\\u00f6ln']                = 'Köln'
dico_correct['Legan\\u00e9s']             = 'Leganés'
dico_correct['Saint']                     = 'Saint-étienne'
dico_correct['Saint-\\u00c9tienne']       = 'Saint-étienne'
dico_correct['\\u00c9tienne']             = 'Saint-étienne'

club.name                                   = club.name.replace(dico_correct)
match[['home_club', 'away_club', 'winner']] = match[['home_club', 'away_club', 'winner']].replace(dico_correct)

# Correction des lignes concernant les matchs à domicile de Saint-étienne
dico_correct = dict()
dico_correct['2017-08-05 18:00:00'] = 'Nice'
dico_correct['2017-08-19 18:00:00'] = 'Amiens SC'
dico_correct['2017-10-14 18:00:00'] = 'Metz'
dico_correct['2017-10-20 18:45:00'] = 'Montpellier'
dico_correct['2017-11-05 20:00:00'] = 'Olympique Lyonnais'
dico_correct['2017-12-15 19:45:00'] = 'Monaco'
dico_correct['2018-01-14 14:00:00'] = 'Toulouse'
dico_correct['2018-01-27 19:00:00'] = 'Caen'
dico_correct['2018-03-18 16:00:00'] = 'Guingamp'
dico_correct['2018-04-22 15:00:00'] = 'Troyes'
dico_correct['2018-05-06 13:00:00'] = 'Bordeaux'
dico_correct['2018-05-19 19:00:00'] = 'Lille'

cond = (match.home_club == 'Saint-étienne') & (match.dateutc.isin(dico_correct.keys()))
match.loc[cond, 'away_club'] = match.loc[cond, 'dateutc'].apply(lambda x: dico_correct[x])

## Re-typage + tri
match.dateutc = match.dateutc.apply(lambda x: dt.datetime.strptime(x, '%Y-%m-%d %H:%M:%S'))
match = match.sort_values(by=['dateutc'])

## Récupération du poste de chaque joueur dans la table « match_event » depuis la table « player »
match_event = match_event.join(player['position'], on='players_id')

In [6]:
## Chargement de la table « match_results » si celle-ci existe déjà
try:
    match_results = pd.read_csv('match_results.csv', index_col=0)
except FileNotFoundError:
    print("/!\ Le fichier « match_results.csv » n'existe pas encore !")

## Chargement de la table « match_infos » si celle-ci existe déjà
try:
    match_infos = pd.read_csv('match_infos.csv', index_col=0)
except FileNotFoundError:
    print("/!\ Le fichier « match_infos.csv » n'existe pas encore !")

## Chargement de la table « match_all » si celle-ci existe déjà
try:
    match_all = pd.read_csv('match_all.csv', index_col=0)
except FileNotFoundError:
    print("/!\ Le fichier « match_all.csv » n'existe pas encore !")

## Chargement de la table « data » si celle-ci existe déjà
try:
    data = pd.read_csv('data.csv', index_col=0)
except FileNotFoundError:
    print("/!\ Le fichier « data.csv » n'existe pas encore !")

## II - Création des tables contenant les variables explicatives

### 1. Création de la table « match_results » (extraction depuis la table « match »)

In [7]:
## Création de la table « match_results »
match_results = Collect_results(match)

In [8]:
## Affichage pour vérification
match_results[-6:].T

,2674,2675,2676,2677,2678,2679
Date,2018-05-20 18:45:00,2018-05-20 18:45:00,2018-05-20 18:45:00,2018-05-20 18:45:00,2018-05-20 18:45:00,2018-05-20 18:45:00
Club,Barcelona,Real Sociedad,Sassuolo,Roma,Lazio,Internazionale
Club_ADV,Real Sociedad,Barcelona,Roma,Sassuolo,Internazionale,Lazio
Période_jour,4,4,4,4,4,4
Arbitre_id,383,383,338,338,356,356
Match_id,760,760,1,1,0,0
Dom_Ext,1,0,1,0,1,0
CLB_Série_vic,26,14,11,22,21,19
CLB_Tot_buts_pour,81,58,21,55,77,57
CLB_Tot_buts_contre,17,50,50,23,36,22
CLB_Tot_buts_diff,64,8,-29,32,41,35
CLB_Série_vic_5,4,3,4,4,5,3
CLB_Tot_buts_pour_5,18,9,6,10,17,13
CLB_Tot_buts_contre_5,10,6,5,4,6,6
CLB_Tot_buts_diff_5,8,3,1,6,11,7
CLB_Série_vic_3,2,2,2,3,3,1
CLB_Tot_buts_pour_3,13,6,4,8,9,7
CLB_Tot_buts_contre_3,8,4,5,1,3,5
CLB_Tot_buts_diff_3,5,2,-1,7,6,2
CLB_Série_vic_1,0,1,1,1,1,0
CLB_Tot_buts_pour_1,4,3,2,1,1,1
CLB_Tot_buts_contre_1,5,2,1,0,0,2
CLB_Tot_buts_diff_1,-1,1,1,1,1,-1
CLB_Nb_jours,7,8,8,14,21,8
ADV_Série_vic,14,26,22,11,19,21
ADV_Tot_buts_pour,58,81,55,21,57,77
ADV_Tot_buts_contre,50,17,23,50,22,36
ADV_Tot_buts_diff,8,64,32,-29,35,41
ADV_Série_vic_5,3,4,4,4,3,5
ADV_Tot_buts_pour_5,9,18,10,6,13,17
ADV_Tot_buts_contre_5,6,10,4,5,6,6
ADV_Tot_buts_diff_5,3,8,6,1,7,11
ADV_Série_vic_3,2,2,3,2,1,3
ADV_Tot_buts_pour_3,6,13,8,4,7,9
ADV_Tot_buts_contre_3,4,8,1,5,5,3
ADV_Tot_buts_diff_3,2,5,7,-1,2,6
ADV_Série_vic_1,1,0,1,1,0,1
ADV_Tot_buts_pour_1,3,4,1,2,1,1
ADV_Tot_buts_contre_1,2,5,0,1,2,0
ADV_Tot_buts_diff_1,1,-1,1,1,-1,1
ADV_Nb_jours,8,7,14,8,8,21
[Résultat],1,0,0,1,0,1
[CLB_Buts],1,0,0,1,2,3
[ADV_Buts],0,1,1,0,3,2

In [9]:
# Écriture de la table « match_results »
match_results.to_csv('match_results.csv', sep=',')

### 2. Création de la table « match_infos » (extraction depuis la table « match_event »)

In [10]:
## Vérification des informations produites par la procédure « Collect_infos »

## Sélection du match pour vérification
match_id = 985

## Lancement de la procédure « Collect_infos » + récupération de la sortie
current_match = match_event[match_event.match_id == match_id].sort_values(by=['matchperiod', 'eventsec'])
meta_data, infos = Collect_infos(current_match)

## Sélection des joueurs pour vérification
players = [str(p) for p in meta_data.keys()]
players = sorted(players[7:])

## Traitement de la sortie pour un meilleur affichage
types      = ['Activité_1H', 'Arrêts_1H', 'Fautes_1H', 'Passes_1H', 'Tirs_1H',
              'Activité_2H', 'Arrêts_2H', 'Fautes_2H', 'Passes_2H', 'Tirs_2H']
to_display = []
for player in players:
    to_display += infos.filter(regex='.*_' + player + '_.*', axis=1).values.tolist()

## Affichage
pd.DataFrame(to_display, index=players).set_axis(types, axis=1).T

,1460,150,161,1673,1739,1839,2065,2162,2215,282,287,304,3217,3234,3235,359,378,442,575,71
Activité_1H,26.0,14.0,15.0,18.0,16.0,12.0,35.0,50.0,0.0,28.0,30.0,0.0,0.0,32.0,0.0,31.0,20.0,26.0,0.0,24.0
Arrêts_1H,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Fautes_1H,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
Passes_1H,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Tirs_1H,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Activité_2H,24.0,11.0,21.0,37.0,23.0,9.0,28.0,34.0,20.0,44.0,25.0,12.0,29.0,45.0,5.0,45.0,19.0,28.0,4.0,34.0
Arrêts_2H,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Fautes_2H,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
Passes_2H,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Tirs_2H,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
match_infos = None

## Boucle sur l'ensemble des matchs présent dans la table « match_results »
for match_id in match_results.Match_id.unique():
    # Récupération des événements du match courant
    current_match = match_event[match_event.match_id == match_id].sort_values(by=['matchperiod', 'eventsec'])
    
    # Collecte des informations sur le match courant
    meta_infos, infos = Collect_infos(current_match)
    
    # Agrégation des informations collectées ci-avant
    if match_infos is None:
        n_index, match_infos = Aggregate_infos(match_id, meta_infos, infos)
    else:
        n_index, stats = Aggregate_infos(match_id, meta_infos, infos, n_index)
        match_infos    = match_infos.append(stats)

## Ré-ordination des colonnes
match_infos = match_infos.reindex(sorted(match_infos.columns, reverse=True), axis=1)

In [12]:
## Vérification des informations produites par la procédure « Aggregate_infos »

## Sélection du match à regarder
match_id = 985

## Affichage
match_infos[match_infos.Match_id == match_id].T

                           1228   1229
Équipe_id                  59.0    6.0
Match_id                  985.0  985.0
(Tirs_Équipe_2H)            1.0    0.0
(Tirs_Équipe_1H)            2.0    0.0
(Tirs_Milieux_2H)           0.0    0.0
(Tirs_Milieux_1H)           1.0    0.0
(Tirs_Défenseurs_2H)        0.0    0.0
(Tirs_Défenseurs_1H)        0.0    0.0
(Tirs_Attaquants_2H)        1.0    0.0
(Tirs_Attaquants_1H)        1.0    0.0
(Passes_Équipe_2H)          1.0    5.0
(Passes_Équipe_1H)          2.0    6.0
(Fautes_Équipe_2H)          4.0    0.0
(Fautes_Équipe_1H)          2.0    2.0
(Fautes_Milieux_2H)         2.0    0.0
(Fautes_Milieux_1H)         0.0    1.0
(Fautes_Gardiens_2H)        0.0    0.0
(Fautes_Gardiens_1H)        0.0    0.0
(Fautes_Défenseurs_2H)      0.0    0.0
(Fautes_Défenseurs_1H)      0.0    1.0
(Fautes_Attaquants_2H)      2.0    0.0
(Fautes_Attaquants_1H)      2.0    0.0
(Arrêts_Gardiens_2H)        0.0    1.0
(Arrêts_Gardiens_1H)        0.0    0.0
(Activité_Équipe_2H)      245.0  347.0
(Activité_Équipe_1H)      262.0  274.0
(Activité_Milieux_2H)     105.0  130.0
(Activité_Milieux_1H)     128.0   66.0
(Activité_Défenseurs_2H)  115.0  161.0
(Activité_Défenseurs_1H)  106.0  131.0
(Activité_Attaquants_2H)   25.0   56.0
(Activité_Attaquants_1H)   28.0   77.0

In [13]:
# Écriture de la table « match_infos »
match_infos.to_csv('match_infos.csv', sep=',')

### 3. Augmentation de la table « match_infos »

In [14]:
## Récupération des noms des clubs dans la table « match_infos » depuis la table « club »
match_infos.insert(2, 'Club', match_infos.join(club.name, on='Équipe_id').name)

## Récupération de la date des match dans la table « match_infos » depuis la table « match_results »
match_infos.insert(0, 'Date', pd.merge(match_results[['Match_id', 'Club', 'Date']], match_infos[['Match_id', 'Club']], on=['Match_id', 'Club']).Date)

## Tri sur le champs 'Date'
match_infos = match_infos.sort_values('Date').reset_index(drop=True)

In [15]:
## Traitement des informations présentes dans « match_infos » + création de variables explicatives
match_infos = pd.concat([match_infos, Exploit_infos(match_infos)], axis=1)

In [16]:
## Affichage
match_infos[match_infos.Club == 'Toulouse'].T

,0,36,116,158,277,463,565,634,807,955,...,1631,1695,2011,2152,2201,2351,2432,2523,2590,2652
Date,2017-08-04 18:45:00,2017-08-12 18:00:00,2017-08-20 19:00:00,2017-08-26 18:00:00,2017-09-15 18:45:00,2017-09-24 19:00:00,2017-10-14 18:00:00,2017-10-21 18:00:00,2017-11-04 19:00:00,2017-11-25 19:00:00,...,2018-02-03 19:00:00,2018-02-10 16:00:00,2018-03-11 20:00:00,2018-04-01 19:00:00,2018-04-07 18:00:00,2018-04-21 18:00:00,2018-04-29 13:00:00,2018-05-06 15:00:00,2018-05-12 19:00:00,2018-05-19 19:00:00
Équipe_id,86,86,86,86,86,86,86,86,86,86,...,86,86,86,86,86,86,86,86,86,86
Match_id,759,746,730,727,709,690,678,665,647,624,...,526,519,470,451,447,427,412,406,392,388
Club,Toulouse,Toulouse,Toulouse,Toulouse,Toulouse,Toulouse,Toulouse,Toulouse,Toulouse,Toulouse,...,Toulouse,Toulouse,Toulouse,Toulouse,Toulouse,Toulouse,Toulouse,Toulouse,Toulouse,Toulouse
(Tirs_Équipe_2H),0,2,0,5,4,0,6,0,0,0,...,0,0,7,0,9,4,0,1,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Tirs_Tot_2H_3,NaN,NaN,NaN,2,7,9,9,10,6,6,...,8,8,8,7,7,16,13,13,5,1
Tirs_Tot_2H_1,NaN,0,2,0,5,4,0,6,0,0,...,8,0,0,7,0,9,4,0,1,0
Tirs_Tot_3H_5,NaN,NaN,NaN,NaN,NaN,23,23,28,28,21,...,28,28,18,27,27,28,40,37,33,33
Tirs_Tot_3H_3,NaN,NaN,NaN,7,14,16,16,21,12,12,...,15,15,18,12,12,25,28,28,17,5
Tirs_Tot_3H_1,NaN,0,7,0,7,9,0,12,0,0,...,15,0,3,9,0,16,12,0,5,0

In [17]:
# Écriture de la table « match_infos » augmentée
match_infos.to_csv('match_infos_aug.csv', sep=',')

### 4. Création de la table « match_all »

In [18]:
## Jointure entre les tables « match_results » et « match_infos »
match_all = pd.merge(match_results, match_infos.drop(['Date', 'Équipe_id'], axis=1), on=['Match_id', 'Club'])

## Auto-jointure pour la récupération des variables explicatives concernant les clubs adverses
match_all = pd.merge(match_all, match_all.filter(regex='(Date|Club$|^Act_.*|^Gar_.*|^Fte_.*|^Pass_.*|^Tirs_.*)', axis=1).rename(columns={'Club': 'Club_ADV'}), how='inner', on=['Date', 'Club_ADV'])

## Fonction pour le renommage des colonnes après l'auto-jointure
def renameCols(name):
    if name[-2:] == '_x':
        return 'CLB_' + name[:-2]
    elif name[-2:] == '_y':
        return 'ADV_' + name[:-2]
    else:
        return name

## Renommage des colonnes
match_all.columns = match_all.columns.map(renameCols)

In [19]:
## Affichage
match_all.iloc[-2:, :].T

                                  2678                 2679
Date               2018-05-20 18:45:00  2018-05-20 18:45:00
Club                             Lazio       Internazionale
Club_ADV                Internazionale                Lazio
Période_jour                         4                    4
Arbitre_id                         356                  356
...                                ...                  ...
ADV_Tirs_Tot_2H_3                   16                    5
ADV_Tirs_Tot_2H_1                   11                    0
ADV_Tirs_Tot_3H_5                   42                   33
ADV_Tirs_Tot_3H_3                   23                   12
ADV_Tirs_Tot_3H_1                   16                    0

[182 rows x 2 columns]

In [20]:
# Écriture de la table « match_all »
match_all.to_csv('match_all.csv', sep=',')